<?php
require '../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

// オプション設定
$options = new Options();
// デフォルトフォント
$options->set('defaultFont', 'sans-serif');
// HTML5タグを有効化
$options->set('isHtml5ParserEnabled', true);

// インスタンス化
$dompdf = new Dompdf($options);

// HTMLコンテンツ
$html = '
<style>
    h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; }
    p { font-size: 14px; line-height: 1.6; }
</style>
<h1>Dompdf Sample</h1>
<p>Hello! This is a PDF generated by dompdf.</p>
';

// 読み込みとレンダリング
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait'); // A4サイズ・縦
$dompdf->render();

// 出力（ブラウザで表示）
$dompdf->stream("sample.pdf", ["Attachment" => false]);
